version: '3.8'

services:
  weather-api:
    build: .
    ports:
      - "8002:80"
    environment:
     - WEATHER_API_KEY
     - WEATHER_BASE_URL
     - CACHE_EXPIRATION_MINUTES
     - AWS_DYNAMO_DB_URL
     - AWS_S3_URL
     - AWS_S3_BUCKET
     - AWS_REGION
     - AWS_ACCESS_KEY_ID
     - AWS_SECRET_ACCESS_KEY
    volumes:
      - .:/app
  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server /data

volumes:
  dynamodb-data:
  minio-data:
